FROM python:3.11

RUN apt-get update && apt-get install -y gettext libgettextpo-dev tidy && apt-get clean

WORKDIR /app
COPY bookwyrm-src/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/static /app/images /app/media

COPY bookwyrm-src/ /app/

EXPOSE 8000
